repos:
# Code Quality Hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ['--line-length', '100']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black']

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length', '100', '--extend-ignore', 'E203']

-   repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
    -   id: pylint
        args: ['--disable=C0111,C0103,C0303,C0330,C0326', '--max-line-length=100']

# Security Hooks
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['-x', 'tests/,venv/']

# Temporarily disabled due to configuration issues
#-   repo: https://github.com/Yelp/detect-secrets
#    rev: v1.4.0
#    hooks:
#    -   id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']

# Type Checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]

# Project-specific Hooks
-   repo: local
    hooks:
    -   id: validate-llm-config
        name: Validate LLM Provider Configuration
        entry: python -c "import config; print('LLM providers validated successfully!')"
        language: system
        files: 'config\.py'
        pass_filenames: false

    -   id: check-code-executor
        name: Check Code Executor Security
        entry: python -c "import code_executor; print('Code executor security checks passed!')"
        language: system
        files: 'code_executor\.py'
        pass_filenames: false
