name: Documentation

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.py'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.py'
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle sphinx sphinx_rtd_theme myst-parser
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check docstring style with pydocstyle
        run: pydocstyle --convention=numpy

      - name: Build documentation
        run: |
          mkdir -p docs
          if [ ! -f docs/conf.py ]; then
            sphinx-quickstart -q --sep \
              -p "AI-ML Code Interviewer" \
              -a "AI-ML Team" \
              -v "1.0" \
              --ext-autodoc \
              --ext-viewcode \
              --ext-todo \
              docs/

            # Update conf.py to use the Read the Docs theme
            echo "import os" >> docs/conf.py
            echo "import sys" >> docs/conf.py
            echo "sys.path.insert(0, os.path.abspath('..'))" >> docs/conf.py
            echo "extensions.append('myst_parser')" >> docs/conf.py
            echo "html_theme = 'sphinx_rtd_theme'" >> docs/conf.py
          fi

          # Generate API documentation
          sphinx-apidoc -o docs/api .

          # Build HTML documentation
          sphinx-build -b html docs docs/_build/html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/_build/html/
