# Dockerfile.streamlit
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY streamlit_app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit application code
COPY streamlit_app/app.py ./

# Expose Streamlit port
EXPOSE 8501

# Run the Streamlit application
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.host=0.0.0.0"]
