version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - WEAVIATE_HOST=weaviate
    networks:
      - vector-network

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate
    networks:
      - vector-network
    volumes:
      - ./streamlit:/app  # Mount the local directory to the /app directory in the container

networks:
  vector-network:
    driver: bridge
